<div class="list">
    @{if Environment::getUser()->isAuthenticated()}
	<div id="post-form-wrapper">
	    @{widget form}
	</div>
    @{/if}

    @{foreach $posts AS $post}
	<hr style="clear:both; visibility:hidden; margin: 0;" />
	<div class="item">
	    {if Misc::isAllowedToControl($post->user)}
	    <div class="control">
		{assign confirm => System::translate("Are you sure you want to delete a discussion post?")}
		{assign link    => $component->link('delete', $post->getId())}
		<a onclick="if(confirm('{!$confirm}')) window.location = '{!$link}'">
		    <img src="{$baseUri . 'img/ico/delete.png'}" alt="{_'Delete'}" />
		</a>
	    </div>
	    {/if}
	    <img class="icon" src="{$post->user, 50|userico}" />
	    <div class="info">
		@{$post->inserted|date} | <strong class="author">{$post->userName}</strong>
	    </div>
	    <div class="content">
			{!=$post->content|texy}
	    </div>
	</div>
    @{/foreach}
    
</div>

@{widget paginator}