<div class="posts list">
    @{if Environment::getUser()->isAuthenticated() && $enablePosting}
	<div id="post-form-wrapper">
	    @{widget form}
	</div>
    @{/if}

    @{foreach $posts AS $post}
		<div class="clear"></div>
		<div class="item">
			<div class="info-side">
				<img class="achievement" title="{_"level based on number of user's discussion posts"}" alt="{_"level based on number of user's discussion posts"}" src="{$baseUri}img/achievement_posts_vertical_small_{$achievements[$post->user]->posts}.png" />
				<img class="icon" src="{$post->user, 50|userico}" />
				<span class="date">{$post->inserted|date}</span>
			</div>
			<div class="info-top">
				<a href="{plink User:default, $post->user}" title="{$post->userName}">{$post->userName|hardTruncate, 20}</a>
				{if Environment::getUser()->isAllowed(Resource::create($post), Action::EDIT)}
					<div class="control">
						<?php $confirm = System::translate("Are you sure you want to delete a discussion post?"); ?>
						{assign link    => $component->link('delete', $post->getId())}
						<a onclick="return confirm('{!$confirm}')" href="{!$link}" title="{_'Delete'}">
							<img src="{$baseUri . 'img/ico/delete.png'}" alt="{_'Delete'}" />
						</a>
					</div>
				{/if}
			</div>
			<div class="content">
				{!=$post->content|texySafe}
			</div>
			<div class="info-bottom">
				{if $enableLinks}
					<a class="control" href="{plink Discussion:Posts,$post->discussed,$post->discussionType}" title="{_"This link will only show the thread where the post was found."}">{_"Link to discsussion"}</a>
				{/if}
			</div>
			<div class="clear"></div>
		</div>
    @{/foreach}

</div>

@{widget paginator}