@{extends layout.phtml}

@{block #subcontent}
	<h1>{_'Social networks'}</h1>
	<p>{_'Here you can see and manage connections with social networks.'}</p>
	<p>{_'Add new social network:'}</p>
	<ul>
		<li>{if isSet($used['facebook'])}{_'Facebook'} | <small>{_'You have already connected to this network.'}</small>{else}<a href="{link facebook}">{_'Facebook'}</a>{/if}</li>
		<li>{if isSet($used['twitter'])}{_'Twitter'} | <small>{_'You have already connected to this network.'}</small>{else}<a href="{link twitter}">{_'Twitter'}</a>{/if}</li>
	</ul>
	{if $flashes}
		<ul>
			{foreach $flashes as $flash}
				<li>{$flash->message}</li>
			{/foreach}
		</ul>
	{/if}
	{if count($data) > 0}
		<table>
			<thead>
				<th>{_'ID'}</th>
				<th>{_'Service/website'}</th>
				<th>{_'Action'}</th>
			</thead>
			<tbody>
				{foreach $data as $row}
					<tr>
						<td>{$row->id_connection}</td>
						<td>{$row->type}</td>
						<td><a href="{link delete,$row->id_connection}">{_'Delete'}</a></td>
					</tr>
				{/foreach}
			</tbody>
		</table>
	{else}
		<p><em>{_'Your account is not connected with any account on social networks.'}</em></p>
	{/if}
	
{/block}