<style>
    .book-list-item {
	width: 30%;
	float: left;
	margin: 0 1% 20px 1%;
    }
    .book-list-item h2 a {
	color: #F1C11B;
    }
</style>

<div clas="book-list">
    {foreach $books AS $book}
    <div class="book-list-item">
	<div class="cover">
	    <img class="icon" src="{$covers[$book->getId()],50|thumbnail}" alt="{$book->title}" width="50" height="80" />
	</div>
	<h2><a href="{plink Book:default,$book->getId()}">{$book->title}</a></h2>
	<div class="info">
	    {foreach $authors[$book->bookNode] AS $author}
	    <a href="" class="author">
		{if $author->groupname != NULL}{$author->groupname} {/if}
		{if $author->firstname != NULL}{$author->firstname}{/if}
		{if $author->lastname != NULL}{$author->lastname}{/if}
	    </a>
	    {/foreach}
	</div>
	<div class="rating"><img src="{$baseUri}img/rating_{=round($book->rating)}.png" /></div>
	<div class="tags">
	    {if isset($tags[$book->bookNode])}
	    {foreach $tags[$book->bookNode] AS $tag}
	    <a href="" class="tag">
		{$tag->name}
	    </a>
	    {/foreach}
	    {/if}
	</div>
    </div>
    {if $iterator->getCounter() % 3 == 0}<div class="clear"></div>{/if}
    {/foreach}
</div>
<hr style="clear:both; visibility:hidden" />
{widget paginator}