<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link rel="stylesheet" type="text/css" href="/css/main.css" />
                <link rel="stylesheet" type="text/css" href="/css/forms.css" />
                <link rel="stylesheet" type="text/css" href="/css/flashes.css" />

		<!--[if lt IE 7.]>
			<script defer type="text/javascript" src="/js/pngfix.js"></script>
		<![endif]-->
		<script type="text/javascript" src="/js/jquery-1.4.2.min.js"></script>
		<script type="text/javascript" src="/js/jquery-ui-1.7.1.custom.min.js"></script>
		<script type="text/javascript" src="/js/jquery.nette.js"></script>
                <script type="text/javascript" src="/js/jquery.ajaxfor­m.js"></script>
		<title>
			{if $pageTitle}
				{$pageTitle}
				-
			{/if}
			Leganto
		</title>
	</head>
	<body>

		<div id="header">
			<div class="wrapper">
				<div id="logo">
					<img id="logo_image" src="/img/logo.png" alt="{_'Logo - opened book'}" />
					<h1>Leganto</h1>
					<span class="motto">{_'Our motto, short, simple'}</span>
					
				</div>
           	{widget search}
			</div>
		</div>

		{widget navigation}

		<div id="main">
			<div class="wrapper">
                            <div id="flashes">
                                {foreach $flashes AS $flash}
                                <div class="flash {$flash->type}">
                                        {$flash->message}
                                    </div>
                                {/foreach}
                            </div>
                @{block #content}
			{_'No content'}
		@{/block}
			</div>
		</div>

		<div id="footer">
			<div class="wrapper"></div>
		</div>

	</body>
</html>
