<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

		<meta name="description" content="{$pageDescription}" n:ifset="$pageDescription" />
		<meta name="keywords" content="{$pageKeywords}" n:ifset="$pageKeywords" />
		<meta name="authors" content="Jan Papoušek, Jan Drábek {_"and our community, altogether."}" />
		
		<link rel="stylesheet" type="text/css" href="/css/main.css" />
		<link rel="stylesheet" type="text/css" href="/css/theme.css" />
		<link rel="stylesheet" type="text/css" href="/css/forms.css" />
		<link rel="stylesheet" type="text/css" href="/css/flashes.css" />
		<link rel="stylesheet" type="text/css" href="/css/lists.css" />

		<script type="text/javascript" src="/js/jquery-1.4.2.min.js"></script>
		<script type="text/javascript" src="/js/search.js"></script>
		<link rel="stylesheet" type="text/css" href="/css/jquery.ui.autocomplete.css" />
		<script type="text/javascript" src="/js/jquery.external.js"></script>
		<script type="text/javascript" src="/js/jquery-ui-1.8.2.custom.min.js"></script>
		<script type="text/javascript" src="/js/jquery.ui.stars.min.js"></script>
		<link rel="stylesheet" type="text/css" href="/css/jquery.ui.stars.min.css" />
		<script type="text/javascript" src="/js/ratings.js"></script>
		<script type="text/javascript" src="/js/jquery.nette.js"></script>
		<script type="text/javascript" src="/js/jquery.ajaxform.js"></script>
		<script type="text/javascript" src="/js/jquery.autocomplete.js"></script>
		<script type="text/javascript" src="/other/texyla/js/texyla.js"></script>
	

		<link rel="image_src" href="<? echo Environment::getHttpRequest()->uri->baseUri; ?>img/logoForFB.png" />
		<link rel="shortcut icon" href="/favicon.ico" />

		<title>
			{if $pageTitle}
				{$pageTitle}
				-
			{/if}
			Leganto
		</title>
	</head>
	<body>

		<div id="header">
			<div class="wrapper">
				<a href="/" title="Leganto" id="logo">
					<span id="page-name">Leganto</span>
					<span id="motto">{_'Our motto, short, simple'}</span>
				</a>
				{widget search}
				<div class="clear"></div>
			</div>
		</div>

		{widget navigation}

		<div id="main">
			<div class="wrapper">
                @{block #content}
					{_'No content'}
				@{/block}
				<div class="clear"></div>
			</div>
		</div>

		<div id="footer">
			<div class="wrapper">
				&copy; <a href="{$baseUri}" title="Leganto - {_'Internet reading lists'}">{=System::domain()->uri}</a> - {_'Internet reading lists'} - <a href="{link Help:text, 29}" title="{_'term of use'}">{_'term of use'}</a>
				|
				{assign email => System::domain()->email}
				{_'contact us at'} <a href="mailto:{$email}">{$email}</a>
				|
				{_'created by'}
				<a href="http://jandrabek.cz" title="Jan Drábek">Jan Drábek</a>
				&amp;
				<a href="mailto:jan.papousek@gmail.com" title="Jan Papoušek">Jan Papoušek</a>
		</div>

	</body>
</html>
