<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="css/main.css" />
<title>Leganto</title>
</head>
<body>

    <div id="header">
		<div class="wrapper">
        	<div id="logo">

            </div>
           	{widget search}
        </div>
    </div>

    {widget navigation}

    <div id="main">
    	<div class="wrapper">
	    {block #content}{/block}
        </div>
    </div>

    <div id="footer">
    	<div class="wrapper"></div>
    </div>

</body>
</html>
