<style>
    .user-item {
	width: 30%;
	float: left;
	margin: 0 1% 20px 1%;
    }
    .user-item .content {
	margin-left: 70px;
    }
    .user-item .info {
	margin-left: 70px;
    }
</style>
<div class="user-list">
{foreach $users AS $user}
    <div class="user-item">
	<img class="icon" src="{$user->getId(), 50|userico}" />
	<div class="info">
	    <a href="{plink User:default, $user->getId()}">{$user->nickname}</a>
	</div>
	<div class="content">
		    {!=String::truncate($user->about, 100)|texy}
	</div>
    </div>
    {if $iterator->getCounter() % 3 == 0}<hr style="clear:both; visibility:hidden" />{/if}
    {/foreach}
</div>
<hr style="clear:both; visibility:hidden" />
{widget paginator}