{if Environment::getUser()->isAllowed(Resource::TOPIC, Action::INSERT)}
    {widget form}
{/if}
<div cllass="list">
    {foreach $topics AS $topic}
    <div class="item">
	<img class="icon" src="{$topic->userId, 50|userico}" />
	<div class="info">
	    <strong><a href="{plink Discussion:posts, $topic->getId(), PostSelector::TOPIC}">{$topic->name}</a></strong>
	    <br />
	    <a href="{plink User:default, $topic->userId}">{$topic->userName}</a>
	    <br />
	    {$topic->inserted|date}
	</div>
    </div>
    <hr style="clear:both; visibility:hidden" />
    {/foreach}
</div>
{widget paginator}