{if Environment::getUser()->isAuthenticated()}
    {widget form}
{/if}
<div id="topics">
    {foreach $topics AS $topic}
    <div class="topic">
	<img class="icon" src="{$baseUri . 'storage/users/' . $topic->userId .'.jpg', 50|thumbnail}" />
	<div class="info">
	    <strong><a href="{plink Discussion:posts, $topic->getId(), PostSelector::TOPIC}">{$topic->name}</a></strong>
	    |
	    <a href="{plink User:default, $topic->userId}">{$topic->userName}</a>
	    |
	    {$topic->inserted|date}
	</div>
    </div>
    <hr style="clear:both; visibility:hidden" />
    {/foreach}
</div>
{widget paginator}