{widget flashMessages}

<div class="feed list">
    <table class="navigation">
        <tr>
			{if !empty($allSwitcher)}
				<th>{_"All"}</th>
				<th><a href="{link followed}">{_"Followed"}</a></th>
			{else}
				<th><a href="{link all}">{_"All"}</a></th>
				<th>{_'Followed'}</th>
			{/if}
        </tr>
    </table>

{foreach $feed AS $item}
    <div class="item item-{$item->type}">

		<div class="info-side">
			<img class="icon" src="{$item->userId, 50|userico}" alt="{$item->userNick}" />
			<span class="date">{$item->inserted|date}</span>
		</div>

		<div class="info-top">
			<strong class="title">
			{if $item->type == FeedItemEntity::TYPE_OPINION}
			{!_'<a href="%s" title="%s">%s</a> has an opinion on the book <a href="%s">%s</a>',$presenter->link('User:default', $item->userId), $item->userNick, ExtraString::hardTruncate($item->userNick,20), $presenter->link('Book:default', $item->categoryId), $item->categoryName}
			{else}
			{if $item->type == FeedItemEntity::TYPE_POST}
				{!_'<a href="%s" title="%s">%s</a> has contributed to the discussion <a href="%s">%s</a>',$presenter->link('User:default', $item->userId), $item->userNick, ExtraString::hardTruncate($item->userNick,20), $presenter->link('Discussion:discussion', $item->categoryId), $item->categorySubname == NULL ? $item->categoryName : $item->categoryName . " (" . $item->categorySubname . ")"}
			{/if}
			{/if}
			</strong>
		</div>

		<div class="content">
				<p>{!=String::truncate($item->content, 300)|texySafe|stripTags}</p>
		</div>
		<div class="clear"></div>
    </div>

	<div class="clear"></div>
    
{/foreach}
</div>
{widget paginator}