<div class="item">
	<div class="info-side">
		<img class="icon" src="{$item->userId, 50|userico}" alt="{$item->userNick}" />
		<div class="clear"></div>
		<span class="date">{$item->inserted|date}</span>
	</div>
	<div class="info-top">
		<strong class="title">
			{* Second parameter of link to discussion must be 1 (hardcoded) *}
			{_"User"} <a href="{plink User:default,$item->userId}">{$item->userNick}</a> {_"have just created new discussion"} <a href="{plink Discussion:posts,$content[0],1}">{$content[1]}</a>.
		</strong>
	</div>

	<div class="content">
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>