<div class="item">
	<div class="info-side">
		<span class="date">{$item->inserted|date}</span>
	</div>
	<div class="info-top">
		<strong class="title">
			{_"User"} <a href="{plink User:default,$item->userId}">{$item->userNick}</a> {_"is now following user"} <a href="{plink User:default,$content[0]}">{$content[1]}</a>.
		</strong>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>