<div class="item">
	<div class="info-side">
		<img class="icon" src="{$item->userId, 50|userico}" alt="{$item->userNick}" />
		<div class="clear"></div>
		<span class="date">{$item->inserted|date}</span>
	</div>
	<div class="info-top">
		<strong class="title">
			{_"User"} <a href="{plink User:default,$item->userId}">{$item->userNick}</a> {_"have just contributed new opinion on book"} <a href="{plink Book:default,$content[0]}">{$content[1]}</a>.
		</strong>
	</div>

	<div class="content">
		{if !empty($content[2])}
			{!$content[2]|texySafe}
		{/if}
		<p>{_"Choosen rating"}: <img src="/img/rating_{$content[3]}.png" alt="{$content[3]|rating}" title="{$content[3]|rating}" class="rating" /></p>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>