<div class="item">
	<div class="info-side">
		<img class="icon" src="{$item->userId, 50|userico}" alt="{$item->userNick}" />
		<div class="clear"></div>
		<span class="date">{$item->inserted|date}</span>
	</div>
	<div class="info-top">
		<strong class="title">
			{_"User"} <a href="{plink User:default,$item->userId}">{$item->userNick}</a> {_"just have changed opinion on book"} <a href="{plink Book:default,$content[0]}">{$content[1]}</a>.
		</strong>
	</div>

	<div class="content">
		{if !empty($content[3])}
			<p><em>{!=$content[3]|texySafe|stripTags}</em></p>
		{/if}
		{if !empty($content[2])}
			<p>{!$content[2]|texySafe|stripTags}</p>
		{/if}
		<p>{_"From rating"}: <img src="/img/rating_{$content[4]}.png" alt="{$content[4]|rating}" title="{$content[4]|rating}" class="rating" /> {_"to"} <img src="/img/rating_{=(int)$content[5]}.png" alt="{$content[5]|rating}" title="{$content[5]|rating}" class="rating" /></p>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>