{_"Hi,"}
{_"probably you have just requested new password on Leganto website."}

{_"If you did not ask for a new password, ignore this e-mail. (This code is valid only for 24 hours since its creation.)"}

{_"For finishing your request you have to copy this code and paste it into the page 'Renew password'."}
{_"Link"}: {$url}
{_"Code"}: {$hash}

{_"Afterwards, a new password will be sent to you. I can be changed in Settings."}

{_"Leganto team"}