{_"Hi,"}
{_"probably you have just requested new password on Leganto website."}

{_"If you did not asked for new password. Ignore this mail as this code is only valid 24 hours from its creation."}

{_"For finishing your request you have to copy this code and paste it into page Renew password."}
{_"Code"}: {$hash}

{_"Afterwards, new password will be send to you and can be changed in Settings."}

{_"Leganto team"}