<div class="box" id="submenu">
    <ul>
	{foreach $links AS $link}
	{if $link->getArgs()}
	    <li{if $presenter->getAction() == $link->getAction() && $control->equalArgs($link->getArgs(),$presenter)} class="active"{/if}><a href="{$presenter->link($link->getAction(),$link->getArgs())}" title="{$link->getTitle()}">{$link->getName()}</a></li>
	{else}
	    <li{if $presenter->getAction() == $link->getAction()} class="active"{/if}><a href="{plink $link->getAction()}" title="{$link->getTitle()}">{$link->getName()}</a></li>
	{/if}
	{/foreach}
    </ul>
</div>

{if !empty($events)}
<div class="box" id="actions">
    <ul>
    	{foreach $events AS $link}
			{assign url    => $component->getPresenter()->link($link->getAction(), $link->getArgs())}
			<li class="event {if $presenter->getAction() == $link->getAction()}active{/if}">
					<a href="{!$url}" title="{$link->getTitle()}" {if $link->getConfirm() != NULL}onclick="return (confirm('{!$link->getConfirm()}'))"{/if}>{$link->getName()}</a>
			</li>
	{/foreach}
    </ul>
</div>
{/if}