<form id="search">
    <fieldset>
	    <legend></legend>
	    <input type="text" size="14" name="name" value="Search"/>
	    <input type="submit" value="" />
	    <input type="radio" name="search" value="all" checked/><a href="#" class="select">{_'all'}</a>
	    <input type="radio" name="search" value="book"/><a href="#" class="deselect">{_'books'}</a>
	    <input type="radio" name="search" value="author"/><a href="#" class="deselect">{_'authors'}</a>
	    <input type="radio" name="search" value="reader"/><a href="#" class="deselect">{_'readers'}</a>
    </fieldset>
</form>