<div id="book-info">
	<!-- BOOK COVER -->
	<div id="cover">
		{if empty($edition)}
			<img src="{$cover,150|thumbnail}" alt="{$book->title}" {if empty($cover)}width="150" height="240"{/if} />
		{else}
			<img src="{$edition->image,150|thumbnail}" alt="{$book->title}" {if empty($edition->image)}width="150" height="240"{/if} />
		{/if}
		<strong title="{_"Percentual rating of book (based on users rating)"}" class="rating">{if $book->rating != 0}{=round($book->rating/5*100)}%{/if}</strong>
		<div class="stats">
			<span title="{_"Number of readers"}" class="readers">{$book->numberOfReaders}</span>
			<span title="{_"Number of opinions (users are allowed to let opinion empty)"}" class="opinions">{$book->numberOfOpinions}</span>
		</div>
	</div>
	<!-- BOOK TITLE -->
	<h1>{$book->title}</h1>
	{if $book->subtitle != NULL}<h2>{$book->subtitle}</h2>{/if}
	<!-- STATISTICS -->
    {widget bookStatistics}

	<!-- AUTHORS -->
    {foreach $authors AS $author}
		<h2>
			<a href="{plink Author:default, $author->getId()}" title="{$author->fullname}">
				{$author->fullname}
			</a>
		</h2>
    {/foreach}

	<!-- EDITION INFO -->
    {if !empty($edition)}
		<p>
			{if $edition->isbn10 != NULL}
				<strong>ISBN:</strong>&nbsp;
				{$edition->isbn10}
				<br />
			{/if}
			{if $edition->isbn13 != NULL}
				<strong>ISBN:</strong>&nbsp;
				{$edition->isbn13}
				<br />
			{/if}
			{if $edition->pages != NULL}
				<strong>Pages:</strong>&nbsp;{$edition->pages}
				<br />
			{/if}
			{if $edition->published}
				<strong>Published:</strong>&nbsp;{$edition->published}
			{/if}
		</p>
    {/if}
</div>
<div class="clear"></div>
    