<div id="book-info">
    {if empty($edition)}
	<img class="icon" src="{$cover,150|thumbnail}" alt="{$book->title}" {if empty($cover)}width="150" height="240"{/if} />
    {else}
	<img class="icon" src="{$edition->image,150|thumbnail}" alt="{$book->title}" {if empty($edition->image)}width="150" height="240"{/if} />
    {/if}
    {widget bookStatistics}
    <h1>{$book->title}</h1>
    <img class="rating" src="{$baseUri}img/rating_{=round($book->rating)}.png" />
    {foreach $authors AS $author}
    <h2>
	<a href="{plink Author:default, $author->getId()}" title="{$author->fullname}">
	    {$author->fullname}
	</a>
    </h2>
    {/foreach}
    {if !empty($edition)}
    <p>
	{if $edition->isbn10 != NULL}
	    <strong>ISBN:</strong>&nbsp;
	    {$edition->isbn10}
	    <br />
	{/if}
	{if $edition->isbn13 != NULL}
	    <strong>ISBN:</strong>&nbsp;
	    {$edition->isbn13}
	    <br />
	{/if}
	{if $edition->pages != NULL}
	    <strong>Pages:</strong>&nbsp;{$edition->pages}
	    <br />
	{/if}
	{if $edition->published}
	    <strong>Published:</strong>&nbsp;{$edition->published}
	{/if}
    </p>

    {/if}
</div>
<hr style="clear:both; visibility:hidden" />
@{widget editionList}
@{widget tagList}
@{widget relatedBookList}
<hr style="clear:both; visibility:hidden" />
    