<div id="feed">
	{foreach $books AS $book}
		<div class="column">
			<h2>{$book->title}</h2>
			<img class="avatar_icon" src="{$covers[$book->getId()],100|thumbnail}" />
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Quis nostrud 							exerci tation ex ea commodo consequat.</p>
		</div>
	{/foreach}
</div>
</div>