@{extends layout.phtml}

@{block #subcontent}
    <div id="user-info">
        <img class="icon" src="{$user->getId(),150|userico}" alt="{$user->nickname}" width="150" />
        <h1>{$user->nickname}</h1>
		{if $user->sex != NULL || $user->birthyear != NULL}
			<p>
				{if $user->sex != NULL}
					<strong>{_"Sex"}:</strong>
					{if $user->sex == "female"}
						{_"Female"}
					{else}
						{_"Male"}
					{/if}
					<br />
				{/if}
				{if $user->birthyear != NULL}
				<strong>{_"Birth year"}:</strong> {$user->birthyear}<br />
				{/if}
			</p>
		{/if}
		<div class="clear">&nbsp;</div>
		{if $user->about != NULL}
			<h2>{_"About"}</h2>
			{!$user->about|texySafe}
		{/if}
	</div>
	<div class="clear">&nbsp;</div>
	<h2>{_"Opinions"}</h2>
	@{widget opinionList}

{/block}
