@{extends layout.phtml}

@{block #subcontent}
    <div id="user-info">
        <img class="icon" src="{$user->getId(),150|userico}" alt="{$user->nickname}" width="150" />
        <h1>{$user->nickname}</h1>
		{if $user->sex != NULL}
			<p><strong>Sex:</strong> {_"$user->sex"}</p>
		{/if}
		{if $user->birthyear != NULL}
		<p><strong>Birth year:</strong> {_"{$user->birthyear}"}</p>
		{/if}
		<div class="clear">&nbsp;</div>
		{if $user->about != NULL}
			<h2>About</h2>
			{!$user->about|texySafe}
		{/if}
	</div>
	<div class="clear">&nbsp;</div>
	<h2>Opinions</h2>
	@{widget opinionList}

{/block}
