@{extends ../layout.phtml}

@{block #content}
    <style>
        #user-info {
            padding-left: 30px;
            padding-top: 10px;
        }
        #user-info h1 {
            margin-top: 0;
            padding-top: 0;
        }
    </style>

    <div id="left-column">
	@{widget submenu}
    </div>
    <div id="right-column">
	{widget flashMessages}
	@{block #subcontent}
	@{/block}
    </div>
@{/block}
