@{extends ../layout.phtml}

@{block #content}
    <style>
        #user-info {
            padding-left: 30px;
            padding-top: 10px;
        }
        #user-info h1 {
            margin-top: 0;
            padding-top: 0;
        }
    </style>

    <div id="right">
		@{widget submenu}
    </div>
    <div id="left">
		<div id="content">
			{widget flashMessages}
			@{block #subcontent}
			@{/block}
		</div>
    </div>
@{/block}
