@{extends layout.phtml}

@{block #subcontent}
    @{widget bookView}
	<h2>{_'Tags'}</h2>
	@{widget tagList}
	<h2>{_'Opinions'}</h2>
	{if $opinionCount == 0}
		<p>{_"There are no text opinions, be the one who write the first one!"}</p>
	{else}
		<p>{_'These opinions we choosed for faster overview.'}<br />
		{_"There can be more opinions (even non text) than you see. Please visit"} <a href="{plink Book:opinions, $bookId}" title="{_"Opinions on the book"}">{_"Opinions on the book"}</a>.</p>
	{/if}
	@{widget opinionList}
	<h2>{_'Related books'}</h2>
	{widget relatedBookList}
	<h2>{_'Editions'}</h2>
	@{widget editionList}
{/block}