@{extends ../layout.phtml}

@{block #content}
<style>
    #book-info, #editions, #opinions, #tags, #feed {
	padding-left: 30px;
	padding-top: 10px;
    }
    #book-info .icon {
	float: left;
    }
    #book-info h1 {
	margin-top: 0;
	padding-top: 0;
    }
    #book-info h2 {
	font-size: 1.5em;
    }
    #editions a:hover .icon {
	border-color: black;
    }
    #tags {
	text-align: justify;
    }
    #tags .tag {
	margin-right: 20px;
	font-weight: bolder;
	font-size: 1.2em;
	color: #F5D25A;
    }
    #tags a.tag:hover {
	color: #4C3319;
    }
</style>

<div id="book-view">
    @{widget submenu}
    @{block #subcontent}
    @{/block}
</div>
@{/block}
