@{extends layout.phtml}

@{block #content}
<style>
    #book-menu {
	list-style: none;
	float: left;
	margin-left: -210px;
    }
    #book-menu li {
	display: block;
	text-align: right;
	margin: 0;
	padding: 10px;
	width:150px;
	border-right: 2px solid #F1C11D;
    }
    #book-menu li a {
	font-size: 120%;
	color: #865A2C;
	font-size: 15px;
	font-weight: bolder;
    }
    #book-menu li a:hover {
	color: #4C3319;
    }
    #book-menu .active {
	background-color: #F5D25A;
    }
    #book-info, #editions, #opinions {
	padding: 10px 30px;
    }
    #book-info .icon {
	float: left;
    }
    #book-info h1 {
	margin-top: 0;
	padding-top: 0;
    }
    #book-info h2 {
	font-size: 1.5em;
    }
    #editions a:hover .icon {
	border-width: 3px;
    }
    #opinions .opinion {
	padding: 0px 10px;
    }
    .opinion .content {
	margin-left: 70px;
    }
    .opinion .info {
	margin-left: 70px;
    }
    .opinion .info .rating {
	text-align: right;
	float:right;
    }
    .opinion .info .author {
    }
</style>

<div id="book-view">
    <ul id="book-menu">
	<li class="active"><a href="">{_'General info'}</a></li>
	<li><a href="">{_'Opinions'}</a></li>
	<li><a href="">{_'Similar books'}</a></li>
    </ul>
    <div id="book-info">
	<img class="icon" src="{$baseUri}storage/books/1/13.jpeg" alt="Cover" />
	<h1>Noční hlídka</h1>
	<img class="rating" src="{$baseUri}img/rating_5.png" />
	<h2>Terry Pratchett</h2>
	<h2>Jan Kantůrek</h2>
    </div>
    <hr style="clear:both; visibility:hidden" />
    <div id="editions">
	{foreach array(1,2,3) AS $num}
	<a href="">
	    <img class="icon" src="{$baseUri}storage/books/1/13.jpeg" width="50" height="80" />
	</a>
	{/foreach}
    </div>
    <hr style="clear:both; visibility:hidden" />
    <div id="opinions">
	<h3>Opinions</h3>
	{foreach array(1,2,3) AS $num}
	<div class="opinion">
	    <img class="icon" src="{$baseUri}img/avatar_placeholder.gif" />
	    <div class="info">
		<img class="rating" src="{$baseUri}img/rating_5.png" />
		20.12. 2010 | <strong class="author">User</strong>
	    </div>
	    <div class="content">
	    <p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor turpis posuere sem malesuada venenatis vel vel arcu. Etiam tempor sollicitudin orci, at pretium sem adipiscing eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
	    </p>
	    <p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor turpis posuere sem malesuada venenatis vel vel arcu. Etiam tempor sollicitudin orci, at pretium sem adipiscing eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
	    </p>
	    </div>
	</div>
	<hr style="clear:both; visibility:hidden" />
	{/foreach}
    </div>
</div>
{/block}