{snippet introduction-block}
	@{if isset($hint)}
	<div id="note">
	    <h1>{_'Did you know?'}</h1>
		<img alt="Tip" src="img/ico/light_bulb.png" />
        <div class="leftspacer">&nbsp;</div>
        <div class="rightspacer">&nbsp;</div>
	    {$hint->text}
	</div>
	@{else}
		@{if $state == "login"}
			@{widget "loginForm"}
		@{/if}
		@{if $state == "facebook"}
			<div>
				<h1>{_'Do you have account?'}</h1>
				<p><strong>{_'Yes...'}</strong> {_'If you want to connect this facebook account please log in.'}</p>
				@{widget "facebookForm"}
				<p><strong>{_'No...'}</strong> {_'If you want to create new account please click on button Create new which log in you automatically in just a second.'}</p>
				<ul>
					{foreach $flashes as $flash}
						<li>{$flash->message}</li>
					{/foreach}
				</ul>
				<a href="{link signUpViaFacebook}" id="signup_button">{_'Create new'}</a>
			</div>
		@{/if}
		@{if $state == "twitter"}
			<div>
				<h1>{_'Do you have account?'}</h1>
				<p><strong>{_'Yes...'}</strong> {_'If you want to connect this twitter account please log in.'}</p>
				@{widget "twitterForm"}
				<p><strong>{_'No...'}</strong> {_'If you want to create new account please click on button Create new which log in you automatically in just a second.'}</p>
				<ul>
					{foreach $flashes as $flash}
						<li>{$flash->message}</li>
					{/foreach}
				</ul>
				<a href="{link signUpViaTwitter}" id="signup_button">{_'Create new'}</a>
			</div>
		@{/if}
		@{if $state == "signup"}
			@{widget "signUpForm"}
		@{/if}
	@{/if}

{/snippet}
<div id="info">
    <h1>{_'Welcome!'}</h1>
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Quis nostrud 							exerci tation ex ea commodo consequat.</p>
</div>
<div id="getin">
    <a href="{link changeState,'signup'}" class="ajax" id="signup_button">{_'Sign up'}</a>
    <a href="{link changeState,'login'}" class="ajax" id="login_button">{_'Log in'}</a>
</div>
<hr />
    <a href="{link changeState, 'facebook'}">{_'Login with Facebook'}</a> |
    <a href="{link changeState, 'twitter'}">{_'Login with Twitter'}</a>