{snippet introduction-block}
	<div id="introduction">
		@{if isset($hint)}
		<div id="note">
			<h2>{_'Did you know, that ...?'}</h2>
			<img alt="Tip" src="img/ico/light_bulb.png" />
			<p>{$hint->text}</p>
		</div>
		@{else}
				
			@{if $state == "login"}
				<div id="introduction-form-wrapper">
				{if $flashes}
				<ul>
					{foreach $flashes as $flash}
						<li>{$flash->message}</li>
					{/foreach}
				</ul>
				{/if}
				@{widget "loginForm"}
				</div>
			@{/if}
			@{if $state == "facebook"}
				@{if $enabled}
					<h1>{_'Do you have an account?'}</h1>
					<div id="mentioned-yes">
						<h2>{_'Yes...'}</h2>
						<p>{_'If you want to connect this Facebook account please log in.'}</p>
						@{widget "facebookForm"}
					</div>
					<div id="mentioned-no">
						<h2>{_'No...'}</h2>
						<p>{_"If you want to create a new account please click on the button 'Create' which logs you in automatically in just a second."}</p>
						<ul>
							{foreach $flashes as $flash}
								<li>{$flash->message}</li>
							{/foreach}
						</ul>
						<a href="{link signUpViaFacebook}" id="signup_button">{_'Create'}</a>
					</div>
				@{/if}
			@{/if}
			@{if $state == "twitter"}
				@{if $enabled}
					<h1>{_'Do you have an account?'}</h1>
					<div id="mentioned-yes">
						<h2>{_'Yes...'}</h2>
						<p>{_'If you want to connect this Twitter account please log in.'}</p>
						@{widget "twitterForm"}
					</div>
					<div id="mentioned-no">
						<h2>{_'No...'}</h2>
						<p>{_"If you want to create a new account please click on the button 'Create' which logs you in automatically in just a second."}</p>
						<ul>
							{foreach $flashes as $flash}
								<li>{$flash->message}</li>
							{/foreach}
						</ul>
						<a href="{link signUpViaTwitter}" id="signup_button">{_'Create'}</a>
					</div>
					<div class="clear"></div>
				@{/if}
			@{/if}
			@{if $state == "signup"}
				<div id="introduction-form-wrapper">
				@{widget "signUpForm"}
				</div>
			@{/if}
			@{if $state == "forgotten"}
				<div id="introduction-form-wrapper">
				@{widget "forgottenForm"}
				</div>
			@{/if}
			@{if $state == "renew"}
				<div id="introduction-form-wrapper">
				{if $flashes}
				<ul>
					{foreach $flashes as $flash}
						<li>{$flash->message}</li>
					{/foreach}
				</ul>
				{/if}
				@{widget "renewForm"}
				</div>
			@{/if}
		@{/if}

		@{if $state != "facebook" && $state != "twitter"}
			<div id="info">
				<h1>{_'Welcome!'}</h1>
				<p>{_'Welcome text. Put introduction text here!'}</p>
				<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2F%23%21%2Fpages%2FCtenari%2F137156876307890%3Fref%3Dts&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; margin-top: 20px; height:80px;" allowTransparency="true"></iframe>
			</div>
			<div id="getin">
				<a href="{link changeState,'signup'}" class="ajax" id="signup_button">{_'Sign up'}</a>
				<a href="{link changeState,'login'}" class="ajax" id="login_button">{_'Log in'}</a>
			</div>
			<div class="clear"></div>
			<a href="{link changeState, 'facebook'}">{_'Login with Facebook'}</a> |
			<a href="{link changeState, 'twitter'}">{_'Login with Twitter'}</a> |
			<a href="{link changeState, 'forgotten'}" class="">{_'Forgotten password'}</a>
		@{/if}
	</div>
{/snippet}
