<?php echo '<?xml version="1.0" encoding="UTF-8"?>' ?>

<available xmlns="http://leganto.com/api">

	<resource>
		<link>{link '//book'}</link>
		<schema></schema>
		<description>Náhled jedné knihy</description>
		<parameters>
			<parameter required="true">
				<name>id</name>
				<description>ID knihy</description>
			</parameter>			
		</parameters>
	</resource>

	<resource>
		<link>{link '//author'}</link>
		<schema></schema>
		<description>Náhled jedoho autora</description>
		<parameters>
			<parameter required="true">
				<name>id</name>
				<description>ID autora</description>
			</parameter>
		</parameters>
	</resource>

	<resource>
		<link>{link '//discussions'}</link>
		<schema></schema>
		<description>Výpis diskusních vláken seřazených sestupě podle času.</description>
		<parameters>
			<parameter required="false">
				<name>type</name>
				<!-- TODO: Specifikovat typ -->
				<description>Označuje typ vláken, která chceme zobrazit.</description>
			</parameter>
			<parameter required="false">
				<name>offset</name>
				<description>Číslo, které udává, odkud se má vypisovat.</description>
			</parameter>
			<parameter required="false">
				<name>limit</name>
				<description>Počet vypsaných položek. Maximálně 100.</description>
			</parameter>
		</parameters>
	</resource>

	<resource>
		<link>{link '//opinions'}</link>
		<schema></schema>
		<description>Přehled názorů na knihu</description>
		<parameters>
			<parameter required="true">
				<name>book</name>
				<description>Kniha, ke které se názory vztahují.</description>
			</parameter>
			<parameter required="false">
				<name>user</name>
				<description>ID uživatele. Pokud je vyplněno, jsou názory seřazeny podle podobnosti s daným uživatelem.</description>
			</parameter>
			<parameter required="false">
				<name>offset</name>
				<description>Číslo, které udává, odkud se má vypisovat.</description>
			</parameter>
			<parameter required="false">
				<name>limit</name>
				<description>Počet vypsaných položek. Maximálně 100.</description>
			</parameter>
		</parameters>
	</resource>

	<resource>
		<link>{link '//posts'}</link>
		<schema></schema>
		<description>Výpis diskusních příspěvků k dané entitě.</description>
		<parameters>
			<parameter required="true">
				<name>id</name>
				<description>ID entity</description>
			</parameter>
			<parameter required="true">
				<name>type</name>
				<!-- TODO: Specifikovat -->
				<description>Typ entity</description>
			</parameter>
			<parameter required="false">
				<name>offset</name>
				<description>Číslo, které udává, odkud se má vypisovat.</description>
			</parameter>
			<parameter required="false">
				<name>limit</name>
				<description>Počet vypsaných položek. Maximálně 100.</description>
			</parameter>
		</parameters>
	</resource>

	<resource>
		<link>{link '//shelf'}</link>
		<schema></schema>
		<description>Výpis knih v poličce</description>
		<parameters>
			<parameter required="true">
				<name>id</name>
				<description>ID poličky</description>
			</parameter>
			<parameter required="false">
				<name>offset</name>
				<description>Číslo, které udává, odkud se má vypisovat.</description>
			</parameter>
			<parameter required="false">
				<name>limit</name>
				<description>Počet vypsaných položek. Maximálně 100.</description>
			</parameter>
		</parameters>
	</resource>

	<resource>
		<link>{link '//similarBooks'}</link>
		<schema></schema>
		<description>Výpis podobných knih k dané knize</description>
		<parameters>
			<parameter required="true">
				<name>book</name>
				<description>ID knihy</description>
			</parameter>
			<parameter required="false">
				<name>offset</name>
				<description>Číslo, které udává, odkud se má vypisovat.</description>
			</parameter>
			<parameter required="false">
				<name>limit</name>
				<description>Počet vypsaných položek. Maximálně 100.</description>
			</parameter>
		</parameters>
	</resource>

	<resource>
		<link>{link '//searchUsers'}</link>
		<schema></schema>
		<description>Vyhledávání v uživatelích</description>
		<parameters>
			<parameter required="true">
				<name>query</name>
				<description>Hledaná fráze</description>
			</parameter>
			<parameter required="false">
				<name>offset</name>
				<description>Číslo, které udává, odkud se má vypisovat.</description>
			</parameter>
			<parameter required="false">
				<name>limit</name>
				<description>Počet vypsaných položek. Maximálně 100.</description>
			</parameter>
		</parameters>
	</resource>

	<resource>
		<link>{link '//similarUsers'}</link>
		<schema></schema>
		<description>Výpis podobných uživatelů k danému uživateli</description>
		<parameters>
			<parameter required="true">
				<name>user</name>
				<description>ID uživatele</description>
			</parameter>
			<parameter required="false">
				<name>offset</name>
				<description>Číslo, které udává, odkud se má vypisovat.</description>
			</parameter>
			<parameter required="false">
				<name>limit</name>
				<description>Počet vypsaných položek. Maximálně 100.</description>
			</parameter>
		</parameters>
	</resource>

	<resource>
		<link>{link '//user'}</link>
		<schema></schema>
		<description>Náhled uživatele</description>
		<parameters>
			<parameter required="true">
				<name>id</name>
				<description>ID uživatele</description>
			</parameter>
		</parameters>
	</resource>


	<resource>
		<link>{link '//searchBooks'}</link>
		<schema></schema>
		<description>Vyhledávání v knihách</description>
		<parameters>
			<parameter required="true">
				<name>query</name>
				<description>Hledaná fráze</description>
			</parameter>
			<parameter required="false">
				<name>offset</name>
				<description>Číslo, které udává, odkud se má vypisovat.</description>
			</parameter>
			<parameter required="false">
				<name>limit</name>
				<description>Počet vypsaných položek. Maximálně 100.</description>
			</parameter>
		</parameters>
	</resource>

	<resource>
		<link{link '//login'}</link>
		<schema></schema>
		<description>Zobrazeni aktualne prihlasene identity (dle cookies)</description>
	</resource>

	<resource>
		<link>{link '//logout'</link>
		<schema></schema>
		<description>Odhlaseni aktualne prihlaseneho uzivatele</description>
	</resource>

</available>