<?php echo '<?xml version="1.0" encoding="UTF-8"?>' ?>

<posts xmlns="http://leganto.com/api">
	{foreach $posts AS $post}
	<post>
		<id>{$post->getId()}</id>
		<language>{$post->language}</language>
		<user>
			<id>{$post->user}</id>
			<name>{$post->userName}</name>
		</user>
		<inserted>{$post->inserted}</inserted>
		<subject>{$post->subject}</subject>
		<reply-to>{$post->reply}</reply-to>
		<content>{$post->content}</content>
	</post>
	{/foreach}
</posts>