<div id="navbar">
    <div class="wrapper">
	    <ul id="menu">
	    <li><a href="#">force</a></li><li><a href="#">in</a></li><li><a href="#">this</a></li><li><a href="#">one</a></li><li><a href="#">strong</a></li><li><a href="#">is</a></li>
		</ul>
		<div id="user">
			<a href="#"><img class="avatar_icon" src="img/avatar_tryout.gif" /><span>Drakir</span></a>
			<span>I</span>
			<a href="#" title="Settings"><img src="img/ico/settings.png" /><span>Settings</span></a>
			<a class="logout" href="#" title="Log out"><img src="img/ico/logout.png" /></a>
		</div>
    </div>
</div>