<div id="navbar">
	<div class="wrapper">
		<ul id="menu">
			<li><a href="{plink default:default}">{_'Main page'}</a></li>
			<li><a href="{plink Discussion:default}">{_'Discussion'}</a></li>
			<li><a href="{plink Book:insert}">{_'Insert book'}</a></li>
			<li><a href="#">strong</a></li>
			<li><a href="#">is</a></li>
		</ul>
		{if $user != NULL}
			<div id="user">
                                <a href="{plink User:default, $user->getId()}"><img class="icon" src="{$user->getId(), 50|userico}" /><span>{$user->nickname}</span></a>
				<span>I</span>
				<a href="{plink Settings:}" title="Settings"><img src="/img/ico/settings.png" /><span>{_'Settings'}</span></a>
				<a class="logout" href="{link logout}" title="{_'Log out'}"><img src="/img/ico/logout.png" /></a>
			</div>
		{/if}
	</div>
</div>