<div id="navbar">
	<div class="wrapper">
		<ul id="menu">
			<li><a href="{plink default:default}">{_'Main page'}</a></li>
			<li><a href="#">this</a></li>
			<li><a href="#">one</a></li>
			<li><a href="#">strong</a></li>
			<li><a href="#">is</a></li>
		</ul>
		{if $user != NULL}
			<div id="user">
				<a href="#"><img class="avatar_icon" src="/img/avatar_tryout.gif" /><span>{$user->nickname}</span></a>
				<span>I</span>
				<a href="#" title="Settings"><img src="/img/ico/settings.png" /><span>{_'Settings'}</span></a>
				<a class="logout" href="{link logout}" title="{_'Log out'}"><img src="/img/ico/logout.png" /></a>
			</div>
		{/if}
	</div>
</div>