# Datas for captcha (english and czech)
INSERT INTO `captcha` (`id`, `question`, `answer`,`id_language`) VALUES
('Kolik je dvě plus 3?', '5',1),
('Kolik je 1 plus deset?', '11',1),
('Kolik je 8 děleno čtyřmi?', '2',1),
('Kolik nohou má pes?', '4',1),
('Kolik nohou má člověk?', '2',1),
('Jsou jehličnany opadavé?', 'ne',1),
('Jaká je barva podzimního listí?', 'žlutá',1),
('Kolik dní má týden?', '7',1),
('Kolik dní má víkend?', '2',1),
('Kolik kol má tříkolka?', '3',1),
('Jaká je barva oblohy?', 'modrá',1),
('Jaká je barva slunce?', 'žlutá',1),
('Kolik písmen má slovo pepa?', '4',1),
('Kolik stupňů má pravý úhel?', '90',1),
('Je-li dneska sobota, jaký den byl včera?', 'pátek',1),
('Jaká je barva trávy?', 'zelená',1),
('Bude-li zítra pondělí, co je za den?', 'neděle',1),
('Je-li dnes středa, co bude pozítří?', 'pátek',1),
('Napište druhé číslo z 21, 34, 8.', '34',1),
('Vyberte barvu z maso, modrá, bačkora.', 'modrá',1),
('Jaká je čtvrtá číslice v čísle 945821?', '8',1),
('Jaká je barva červeného vína?', 'červená',1),
('Napište nástroj z myš, preclík, kladivo.', 'kladivo',1);

INSERT INTO `captcha` (`question`, `answer`,`id_language`) VALUES
('Two plus 3 equals?', '5',2),
('1 plus ten equals?', '11',2),
('8 divided by four?', '2',2),
('How many legs dog have?', '4',2),
('How many legs human have?', '2',2),
('Are coniferous deciduous?', 'no',2),
('What is the color of autumn leaves?', 'yellow',2),
('How many days are in week?', '7',2),
('How many days are in weekend?', '2',2),
('How many wheel does tricycle have?', '3',2),
('What is the color of sky?', 'blue',2),
('What is the color of sun?', 'yellow',2),
('How many characters are in the word test?', '4',2),
('How many degrees does right angle have?', '90',2),
('If it is saturday today, what day was yesterday?', 'friday',2),
('What is the color of grass?', 'green',2),
('If tomorow will be monday, what day is today?', 'sunday',2),
('If it is wednesday, what will be the day after tomorow?', 'friday',2),
('Write second number from 21, 34, 8.', '34',2),
('Write color from meat, blue, slipper.', 'blue',2),
('What is the fourth number in 945821?', '8',2),
('What is the color of red wine?', 'red',2),
('Write tool from mouse, pretzl, hammer.', 'hammer',2);