--- Vedeli jste, ze...
--- (pro cestinu = 1)
---

INSERT INTO `help` (`id_help`, `id_language`, `category`, `text`, `image`) VALUES
(1, 1, 'user', 'Můžete použít přihlášení přes Facebook nebo Twitter a zjednodušit si tak přihlášení. Pokud už máte účet, můžete jej se sociální sítí spojit dodatečně z <a href="/settings/">Nastavení</a>.', NULL),
(2, 1, 'other', 'Můžete s ostatními čtenáři diskutovat v sekci <a href="/discussion/">Diskuze</a>. <a href="/help/text?id=49">Více</a>', NULL),
(3, 1, 'book', 'Můžete shlédnout TOP 200 nejlepších knih v sekci <a href="/default/top-books">Nejlepší knihy</a>.', NULL),
(4, 1, 'other', 'Můžete najít další informace o tomto webu a o všemožných úkonech v sekci <a href="/help/">Nápověda</a>.', NULL),
(5, 1, 'other', 'Můžete vyhledávat odděleně knihy, autory, diskuze, uživatele. U vyhledávání knih a autorů můžete použít napovídání (stačí po napsání nejméně dvou znaků chvilku počkat). <a href="/help/text?id=42">Více</a>', NULL),
(6, 1, 'user', 'Můžete u svého účtu vyplnit pohlaví a věk, aby ostatní věděli s kým mají tu čest. Na jejich základě můžete shlédnout působivé statistiky u knih a cíleněji se rozhodovat, kterou knihu si přečtete.', NULL),
(7, 1, 'user', 'Můžete na stránce Aktuální dění rozlišovat, zda je položka novým názorem nebo diskuzí - k tomu slouží ikonka knihy (pro názor) a tužky (pro diskuzní příspěvek) v pravé části položky.', NULL),
(8, 1, 'book', 'Můžete vidět celkové hodnocení knihy nad obálkou a to v podobě procentuálního vyjádření, které je přesnější než počet hvězdiček.', NULL),
(9, 1, 'book', 'Můžete knihy uspořádávat do poliček a v nich můžete nastavit přesné pořadí knih. Můžete tak dosáhnout poličky s nejoblíbenějšími knihami, vlastněnými knihami, knihami právě čtenými, či knihami, které si chcete přečíst. <a href="/help/text?id=46">Více</a>', NULL),
(10, 1, 'user', 'Můžete sledovat jiné uživatele a vidět tak jednoduše jejich nově přidané názory a diskuzní příspěvky. Sledujte své známé, kamarády, uživatele s dobrým vkusem... Seznam uživatelů, které následujete vy, a kteří následují vás, najdete ve vašem profilu. <a href="/help/text?id=50">Více</a>', NULL),
(11, 1, 'user', 'Můžete vidět, kteří uživatelé mají podobné názory na knihy jako vy. Jejich seznam si můžete zobrazit přes váš profil na podstránce Podobní uživatelé.', NULL),
(12, 1, 'other', 'Můžete na stránce Aktuální dění vidět veškeré dění (aktivitu všech uživatelů) na našem serveru. Stačí v horní stránce kliknout na odkaz vše.', NULL),
(13, 1, 'user', 'Můžete vaše příspěvky a názory opatřit vaším avatarem - obličejem, který umožní ostatním čtenářům velice rychle rozpoznat vaše příspěvky. <a href="/help/text?id=41">Více</a>', NULL),
(14, 1, 'other', 'Můžete komentovat názory na knihy. Stačí kliknout na odkaz Odpovědět v pravém dolním rohu názoru a do nově zobrazeného formuláře zadat text vašeho komentáře, či dotazu.', NULL),
(15, 1, 'book', 'Můžete přidat nové klíčové slovo u knihy bez přidání názoru. Na stránce knihy najdete pod klíčovými slovy formulář pro jeho vložení.', NULL),
(16, 1, 'book', 'Můžete řadit názory na stránce knihy (na podstránce názory) podle času nebo hodnocení.', NULL),
(17, 1, 'book', 'Můžete zobrazit podobné knihy nějaké vybrané knihy. Najdete je seřazené od nejpodobnější na stránce knihy na podstránce podobné knihy.', NULL),
(18, 1, 'other', 'Na hlavní stránce se pod virtuální prohlídkou zobrazují poslední přidané názory?', NULL),
(19, 1, 'user', 'Můžete na svou osobní stránku nebo blog umístit ikonku čtenáře (obrázek) s třemi knihami, které jste přidali do svého deníku jako poslední. <a href="/help/text?id=51">Více</a>', NULL),
(20, 1, 'user', 'Můžete si s ostatními uživateli vyměňovat soukromé zprávy? Napsat jim můžete ze svého profilu, stačí pouze znát jejich přezdívku.', NULL),
(21, 1, 'other', 'Můžete vidět u jednotlivých diskuzí čas přidání nejnovějšího příspěvku? Nebo, že můžete vidět počet příspěvků?', NULL),
(22, 1, 'other', 'Diskuze v sekci Diskuze jsou nahoře ty diskuze v nich přibyly nové příspěvky? Díky tomu je snadné lehkce zkontrolovat nové příspěvky.', NULL),
(23, 1, 'book', 'Vám na základě podobných uživatelů můžeme doporučit knihu, která by se vám mohla líbit?', NULL),
(24, 1, 'other', 'Více než dva autoři se sbalí a zobrazí se až po najetí myší?', NULL),
(25, 1, 'book', 'Pokud nastavíte typ poličky na Chci si přečíst nebo Právě čtu, pak se při přidání názoru kniha vyhodí sama? <a href="/help/text?id=46">Více</a>', NULL),
(26, 1, 'book', 'Můžete zobrazit náhodnou knihu kliknutím na odkaz <a href="/book/random">Náhodná kniha</a> na detailu jiné knihy?', NULL),
(27, 1, 'other', 'Můžete v názorech i diskuzních příspěvcích používat formátování? <a href="/help/text?id=64">Více</a>', NULL),
(28, 1, 'other', 'Máme nápovědu, ve které najdete většinu věcí, které vás zajímají? <a href="/help/">Více</a>', NULL),
(29, 1, 'other', 'Můžete na svou stránku vložit interaktivní blok s posledními přečtenými knihami? <a href="/help/text?id=61">Více</a>', NULL),
(30, 1, 'book', 'Pokud si nevíte rady s autorem při vkládání knihy, připravili jsme pro vás <a href="/help/text?id=63">popostrčení</a>?', NULL),
(31, 1, 'other', 'Můžete sdílet svou oblíbenou knihu na sociálních sítích? <a href="/help/text?id=44">Více</a>?', NULL),
(33, 1, 'user', 'Heslo 123456 ani váš oblíbený hokejový tým nejsou bezpečná hesla? <a href="/help/text?id=65">Více</a>?', NULL),
