<script type="text/javascript">
$(document).ready(
    function() {
	$("#book-stats").accordion({
	    event: "mouseover",
	    autoHeight: false
	});
    }
);
</script>
<div>
<div id="book-stats">
    {foreach $graphs AS $graph}
	{if !empty($graph['graph'])}
	    <h3>{$graph['label']}</h3>
	    <div>
		<img src="{$graph['graph']->getLink()}" alt="{$graph['label']}" />
	    </div>
	{/if}
    {/foreach}
</div>
</div>