<style>
    #book-stats {
	float: right;
	min-height: 250px;
    }
    #book-stats h3 {
	padding: 0 10px;
	-webkit-border-radius: 5px;
	-moz-border-radius: 5px;
	border-radius: 5px;
	border: 2px solid #6699bb;
    }
</style>
<script type="text/javascript">
$(document).ready(
    function() {
	$("#book-stats").accordion({
	    event: "mouseover",
	    autoHeight: false
	});
    }
);
</script>
<div>
<div id="book-stats">
    {foreach $graphs AS $graph}
	{if !empty($graph['graph'])}
	    <h3>{$graph['label']}</h3>
	    <div>
		<img src="{$graph['graph']->getLink()}" />
	    </div>
	{/if}
    {/foreach}
</div>
</div>