<?php echo '<?xml version="1.0" encoding="UTF-8"?>' ?>

<similar-users xmlns="http://leganto.com/api">

	{foreach $users AS $similarUser}
	<user>
		<id>{$similarUser->getId()}</id>

		<name>{$similarUser->nickname}</name>

		<registrated>{$similarUser->inserted}</registrated>

		{if !empty($similarUser->lastLogged)}
		<last-logged>{$similarUser->lastLogged}</last-logged>
		{/if}

		{if !empty($similarUser->birthyear)}
		<birth-year>{$similarUser->birthyear}</birth-year>
		{/if}

		{if !empty($similarUser->sex)}
		<sex>{$similarUser->sex}</sex>
		{/if}

		<similarity>{$similarUser->similarity*100}</similarity>
	</user>
	{/foreach}

</similar-users>