<div id="book-shelf-control" class="box">
    <h3>{_'Shelves'}</h3>
    {if !empty($shelves)}
	<ul>
	    {foreach $shelves AS $shelf}
		<li>
		    <span class="control">
			{assign confirm => System::translate("Are you sure you want to remove a book from shelf *%s*?", $shelf->name)}
			{assign link    => $component->link('removeFromShelf', $book->getId(), $shelf->getId())}
			<a onclick="return confirm('{$confirm}')" href="{!$link}">
			    <img src="{$baseUri . 'img/ico/delete.png'}" alt="{_'Delete'}" />
			</a>
		    </span>
		    {$shelf->name}
		</li>
	    {/foreach}
	</ul>
    {/if}
	{widget form}
</div>