<p>Vážení čtenáři,</p>

<p>
	rádi bychom vás, uživatele webu <a href="http://ctenari.cz">ctenari.cz</a>,
	informovali o přechodu tohoto webu na novou adresu a to <a href="http://leganto.cz">leganto.cz</a>
	a také o četných změnách, kterými tyto stránky nedávno prošly.
</p>

<p>
	Změnili a zjednodušili jsme vzhled i ovládací prvky, přidali jsme obálky
	ke knihám a připravili jsme pro vás poličky, kam si můžete knihy zařazovat
	dle vlastních kritérií. Změn je samozřejmě mnohem více. Přihlašte se
	na web <a href="http://leganto.cz">leganto.cz</a>*  a zkuste je objevit všechny!
</p>

<p>
	<a style="font-size: 2em" href="http://leganto.cz">leganto.cz</a><br/>
	"Ne jenom chlebem živ je člověk"
</p>

<p>
	<small>
		PS: Tento e-mail je jednorázovým upozorněním na celkové přepracování
		a změnu adresy webu, na kterém jste se zaregistrovali. Nemusíte se proto bát,
		od provozovatelů webu vám již nebudou chodit žádné další zprávy.
	</small>
</p>

<p>
	<small>
		*Použijte přihlašovací údaje, které jste si nastavili při registraci na webu
		<a href="http://ctenari.cz">ctenari.cz</a>. Pokud jste již zapomněli heslo, můžete si jej snadno obnovit
		(viz odkaz Zapomenuté heslo na uvítací stránce webu). Kdyby se vám přihlášení
		ani poté nezdařilo, neváhejte nás kontaktovat.
	</small>
</p>
