<p>Vážení uživatelé,<br />
webu <a href="http://leganto.cz">leganto.cz</a> (dříve <a href="http://ctenari.cz">ctenari.cz</a>).<br>
Chceme vás informovat, že jsme se rozhodli ukončit provoz webu k 31. srpnu 2016, protože již není v našich<br/>
možnostech web i nadále provozovat.</p>

<p>Ceníme si vašeho dosavadního zájmu a aktivity, díky čemuž se podařilo vytvořit nezanedbatelné množství zajímavého obsahu.<br />
Z tohoto důvodu si můžete na webu do termínu ukončení služeb exportovat své názory a poličky. Konkrétní instrukce najdete <br />
na <a href="http://leganto.cz">leganto.cz</a>, exportovací možnosti najdete ve svém profilu po přihlášení.</p>

<p>Narazíte-li na libovolný problém, nebojte se nás kontaktovat.</p>

<p>S přáním mnoha dalších čtenářských zážitků se loučí<br>
tým Leganto.cz</p>


<p><small>P.S. Jako alternativu můžete pro české a slovenské knihy využít <a href="http://www.databazeknih.cz">Databázi knih</a>.</small></p>

