<style>
    .opinion {
	padding: 0px 10px;
    }
    .opinion .content {
	margin-left: 70px;
    }
    .opinion .info {
	margin-left: 70px;
    }
    .opinion .info .rating {
	text-align: right;
	float:right;
    }
    .posts {
	padding-left: 50px;
    }
    #ordering {
        margin: 10px;
    }
</style>

{snippet opinion-list}
<div class="opinion-list">
    @{foreach $opinions AS $opinion}
    <div class="opinion">
        {if $showedInfo == 'user'}
            <img class="icon" src="{$opinion->userId, 50|userico}" />
        
            <div class="info">
                <img class="rating" src="{$baseUri}img/rating_{$opinion->rating}.png" />
                {$opinion->inserted|date} | <a href="{plink User:default, $opinion->userId}">{$opinion->userName}</a>
            </div>
        {else}
            <img class="icon" src="{$opinion->bookTitleId, 50|bookcover}" />
            
            <div class="info">
                <img class="rating" src="{$baseUri}img/rating_{$opinion->rating}.png" />
                {$opinion->inserted|date} | <a href="{plink Book:default, $opinion->bookTitleId}">{$opinion->bookTitle}</a>
            </div>
        {/if}
        <div class="content">
            {!=$opinion->content|texy}
        </div>
        <div class="posts">
            @{if isset($showedOpinion) && $showedOpinion == $opinion->getId()}
                <div class="posts">
                @{widget postList}
                </div>
            @{else}
                @{if isset($discussions[$opinion->getId()])}
                    <a href="{link showPosts!, $opinion->getId()}" class="show ajax">{_'Show %d comments',$discussions[$opinion->getId()]}</a>
                @{else}
                    @{if Environment::getUser()->isAuthenticated()}
                    <a href="{link showPosts!, $opinion->getId()}" class="show ajax">{_'Reply'}</a>
                    @{/if}
                @{/if}
            @{/if}
        </div>
    </div>
    <hr style="clear:both; visibility:hidden" />
    @{/foreach}

    {widget paginator}
</div>
{/snippet}