<style>
    #share-box {
	border-color: #9F1C1C;
    }
    .share-box-inner {
	margin-left: 20px;
    }
</style>

<div id="share-box" class="box">
    <h3>{_'Share'}</h3>
    <div class="share-box-inner">
	    <a href="http://www.facebook.com/sharer.php?u={$url}&t={$title}" title="{_"Share on facebook"}"><img src="/img/socialnetworks/facebook.png" alt="{_"Share on facebook"}" /></a>
	    <a href="http://twitter.com/home?status={$title} {$url} {_"I like it!"}" title="{_"Share on twitter"}" target="_blank"><img src="/img/socialnetworks/twitter.png" alt="{_"Share on twitter"}" /></a>
	    <a href="http://del.icio.us/post?url={$url}" title="{_"Save to delicious"}"><img src="/img/socialnetworks/delicious.png" alt="{_"Save to delicious"}" /></a>
	    <a href="http://digg.com/submit?url={$url}&amp;title={$title}" title="{_"Share on digg"}"><img src="/img/socialnetworks/digg.png" alt="{_"Share on digg"}" /></a>
	    <a href="https://www.google.com/bookmarks/mark?op=edit&bkmk={$url}&amp;title={$title}" title="{_"Bookmark on google"}"><img src="/img/socialnetworks/google.png" alt="{_"Bookmark on google"}" /></a>
    </div>
</div>