@{extends layout.phtml}

@{block #subcontent}

<style>
    .stat-graph {
	text-align: center;
	margin: 10px 0;
    }

</style>

    <h1>{_'Statistics'}</h1>

    <h2>Opinions by rating</h2>
    <div class="stat-graph">
	<img src="{$opinionsByRating}"  align="center" />
    </div>

    <h2>Opinions inserted in last year</h2>
    <div class="stat-graph">
	<img src="{$opinionsLastYear}" class="stat-graph" align="center" />
    </div>
{/block}