<div id="twitter">
	<h3><a href="http://twitter.com/#!/leganto_devel" title="{_'Leganto on twitter'}">{_'Leganto on twitter'}</a></h3>

	<div id="twitter_div">
		<ul id="twitter_update_list"></ul>
	</div>
	
	<script type="text/javascript" src="http://twitter.com/javascripts/blogger.js"></script>
	<script type="text/javascript" src="http://twitter.com/statuses/user_timeline/leganto_devel.json?callback=twitterCallback2&amp;count=1"></script>
</div>