<h1>{_'Insert book: look if it is mentioned'}</h1>

<div id="mentioned-yes">
	<h2>{_'Yes'}</h2>
	<p>{_'The book already exists on our web. You don\'t have to insert it again. If you want to add your opinion do it from the book detail.'}</p>
</div>
<div id="mentioned-no">
	<h2>{_'No'}</h2>
	<p>{_'Please continue to the next page where you will be asked for some other information.'}</p>
	<p><a href="{link continueToInsert, $title}"><button name="continue_button" value="{_'Continue'}">{_'Continue'}</button></a>
</div>
<div class="clear"></div>
<h2>{_'Found books'}</h2>
{widget searchForm}
{widget bookList}