<style>
    #submenu {
	border-color: #F1C11D;
    }
    #actions {
	border-color: green;
    }
    #submenu ul li, #actions ul li {
	text-align: right;
	padding: 10px 0;
    }
    #submenu li a, #actions li a {
	font-size: 120%;
	color: #865A2C;
	font-size: 15px;
	font-weight: bolder;
    }
    #submenu li a:hover, #actions li a:hover {
	color: #4C3319;
    }
    #submenu .active, #actions .active {
	background-color: #F5D25A;
    }
</style>
<div class="box" id="submenu">
    <ul>
	{foreach $links AS $link}
	{if $link->getArgs()}
	    <li{if $presenter->getAction() == $link->getAction()} class="active"{/if}><a href="{plink $link->getAction(), $link->getArgs()}">{$link->getName()}</a></li>
	{else}
	    <li{if $presenter->getAction() == $link->getAction()} class="active"{/if}><a href="{plink $link->getAction()}">{$link->getName()}</a></li>
	{/if}
	{/foreach}
    </ul>
</div>

{if !empty($events)}
<div class="box" id="actions">
    <ul>
    	{foreach $events AS $link}
	{if $link->getArgs()}
	    <li class="event {if $presenter->getAction() == $link->getAction()}active{/if}"><a href="{plink $link->getAction(), $link->getArgs()}">{$link->getName()}</a></li>
	{else}
	    <li class="event {if $presenter->getAction() == $link->getAction()}active{/if}"><a href="{plink $link->getAction()}">{$link->getName()}</a></li>
	{/if}
	{/foreach}
    </ul>
</div>
{/if}