<style>
    #submenu {
	list-style: none;
	float: left;
	margin-left: -210px;
    }
    #submenu li {
	display: block;
	text-align: right;
	margin: 0;
	padding: 10px;
	width:150px;
	border-right: 2px solid #F1C11D;
    }
    #submenu li a {
	font-size: 120%;
	color: #865A2C;
	font-size: 15px;
	font-weight: bolder;
    }
    #submenu li a:hover {
	color: #4C3319;
    }
    #submenu .active {
	background-color: #F5D25A;
    }
</style>
<ul id="submenu">
    {foreach $links AS $link}
    {if $link->getArgs()}
	<li{if $presenter->getAction() == $link->getAction()} class="active"{/if}><a href="{plink $link->getAction(), $link->getArgs()}">{$link->getName()}</a></li>
    {else}
	<li{if $presenter->getAction() == $link->getAction()} class="active"{/if}><a href="{plink $link->getAction()}">{$link->getName()}</a></li>
    {/if}
    {/foreach}
</ul>