<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="cs" />
	<meta name="copyright" content="&copy; 2009 Jan Drabek, Jan Papousek" />

	<!-- RSS -->
	{foreach $rss AS $url => $name}
		<link rel="alternative" type="application/rss+xml" title="{$name}" href="{plink $url}" />
	{/foreach}

	<!-- CSS -->
	<link rel="stylesheet" type="text/css" href="{$baseUri}fluid960gs/css/reset.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="{$baseUri}fluid960gs/css/text.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="{$baseUri}fluid960gs/css/grid.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="{$baseUri}fluid960gs/css/layout.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="{$baseUri}fluid960gs/css/nav.css" media="screen" />
	<!--[if IE 6]><link rel="stylesheet" type="text/css" href="css/ie6.css" media="screen" /><![endif]-->
	<!--[if IE 7]><link rel="stylesheet" type="text/css" href="css/ie.css" media="screen" /><![endif]-->
	<link rel="stylesheet" type="text/css" href="{$baseUri}css/systemMessages.css" />
	{if !empty($stylesheets)}
		{foreach $stylesheets AS $url => $media}
			<link rel="stylesheet" type="text/css" href="{$url}" media="{$media}" />
		{/foreach}
	{/if}

	<!-- Javascript -->
    <script type="text/javascript" src="{$baseUri}fluid960gs/js/mootools.js"></script>
    <script type="text/javascript" src="{$baseUri}fluid960gs/js/fluid16.js"></script>
    <script type="text/javascript" src="{$baseUri}fluid960gs/js/accordion.js"></script>
    <script type="text/javascript" src="{$baseUri}fluid960gs/js/sectionmenu.js"></script>

	<title>{if isset($title)} {$title} {/if} {if isset($subtitle)} - {$subtitle} {/if}</title>

</head>
<body>
		<div class="container_16">
			<!-- Header -->
			<div class="grid_16">
				<h1 id="branding">
					<a href="">{="site_name"|translate}</a>

				</h1>
			</div>
			<div class="clear"></div>
			<!-- Main menu -->
			<div class="grid_16">
				<ul class="nav">
				{foreach $menu AS $links}
					{foreach $links AS $link}
						<li><a href="{plink $link['url']}" title="{$link['name']}">{$link['name']}</a></li>
					{/foreach}
				{/foreach}
				</ul>
			</div>
			<div class="clear"></div>
			<!-- Page heading -->
			<div class="grid_16">
				<h2 id="page-heading">{$subtitle}</h2>
			</div>
			<div class="clear"></div>
			<!-- Left columns -->
			<div class="grid_4">
				{foreach $components AS $componentsP}
					{foreach $componentsP AS $component}
					<div class="box">
						{!$presenter->getComponent($component)->render()}
					</div>
					{/foreach}
				{/foreach}
			</div>
			<!-- Main content -->
			<div class="grid_8">
				{include @content.phtml}
			</div>
			<!-- Right columns -->
			<div class="grid_4">
				<div class="box">
					<h2>

						<a href="#" id="toggle-paragraphs">Paragraphs</a>
					</h2>
					<div class="block" id="paragraphs">
						<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
						<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
					</div>
				</div>
			</div>
			<div class="clear"></div>
			<!-- Site info -->
			<div class="grid_16" id="site_info">
				<div class="box">
					<p>
						&copy; 2007 - 2009
						<a href="mailto:jan.papousek@gmail.com" title="Jan Papoušek">Jan Papoušek</a>,
						<a href="mailto:repli2dev@gmail.com" title="Jan Drábek">Jan Drábek</a>;
						<a href="mailto:richard.sefr@gmail.com" title="Richard Šefr">Richard Šefr</a>
					</p>
				</div>
			</div>
			<div class="clear"></div>

	</div>
</body>
</html>
