<div id="header">
	<div id="head">
		<div id="section-links">
			<a href="/" title="Čtenářský deník" class="main-link">Čtenářský deník</a>
		</div>
	</div>
		<div id="navigation">
			<div id="navigation-left"></div>
			<div id="navigation-right"></div>
			<h1 id="section">
				<a href="{$section['url']}" title="{$section['name']}">{$section["name"]}</a>
			</h1>
			{include @menu.phtml}
		</div>
</div>
