<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="cs" />
	<meta name="copyright" content="&copy; 2009 Jan Drabek, Jan Papousek" />
	{foreach $rss AS $url => $name}
		<link rel="alternative" type="application/rss+xml" title="{$name}" href="{plink $url}" />
	{/foreach}
	<link rel="stylesheet" type="text/css" href="{$baseUri}css/main.css" />
	<link rel="stylesheet" type="text/css" href="{$baseUri}css/form.css" />
	{if !empty($stylesheets)}
		{foreach $stylesheets AS $url => $media}
			<link rel="stylesheet" type="text/css" href="{$url}" media="{$media}" />
		{/foreach}
	{/if}
	<title>{if isset($title)} {$title} {/if} {if isset($subtitle)} - {$subtitle} {/if}</title>

</head>
	<div id="background">
		{include @header.phtml}
		<div id="body">
			{include @left.phtml}
			{include @content.phtml}
			{include @right.phtml}
		</div>
		<div id="foot">
			&copy; 2007 - 2009
			<a href="mailto:jan.papousek@gmail.com" title="Jan Papoušek">Jan Papoušek</a>,
			<a href="mailto:repli2dev@gmail.com" title="Jan Drábek">Jan Drábek</a>;
			<a href="mailto:richard.sefr@gmail.com" title="Richard Šefr">Richard Šefr</a>
		</div>
	</div>
</html>
