<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="cs" />
	<meta name="copyright" content="&copy; 2009 Jan Drabek, Jan Papousek" />
	<title>{if isset($title)} {$title} {/if} {if isset($subtitle)} {$subtitle} {/if}</title>

</head>
	<div id="container">
		{include @header.phtml}
		
		{include @content.phtml}
		
	</div>
</html>
