<div class="cb"></div>
{if $paginator && $paginator->getPageCount() > 1}
<div class="widebox">
	<div class="tlc"></div>
	<div class="trc"></div>
	<div class="blc"></div>
	<div class="brc"></div>
	<h2 class="fl">Stránkování
	<small>(zobrazena strana {$paginator->getPage()} z {$paginator->getPageCount()})</small>
	</h2>

	<form action="{link page!}" method="get" class="fr m5_10 hl">
	<div>
		<input type="text" name="page" size="4" maxlength="4" value="{$paginator->getPage()}" />
		<input type="submit" name="apply" value="Přejít" />
		{if isset($persistentParams)}
		{foreach $persistentParams as $key => $value}
			{if $key != 'page'}<input type="hidden" name="{$key}" value="{$value}" />{/if}
		{/foreach}
		{/if}
	</div>
	</form>

	<div class="paginator hl">
	{assign $mid_low max(min($paginator->getLastPage() - 2, $paginator->getPage() - 1), $paginator->getFirstPage())}
	{assign $mid_high min(max($paginator->getFirstPage() + 2, $paginator->getPage() + 1), $paginator->getLastPage())}
	<table class="w100 cb">
	<tr>
		<td class="tal">
		{if $paginator->isFirst()}
			<span>&laquo;&nbsp;První</span>
			<span>&lsaquo;&nbsp;Předchozí</span>
		{else}
			<a{if $paginator->getFirstPage() == $paginator->getPage()} class="inactive"{/if} href="{link page!, $paginator->getFirstPage()}"><span>&laquo;&nbsp;První</span></a>
			<a{if $paginator->getFirstPage() == $paginator->getPage()} class="inactive"{/if} href="{link page!, $paginator->getPage() - 1}"><span>&lsaquo;&nbsp;Předchozí</span></a>
		{/if}
		{for $i = $paginator->getFirstPage(); $i < min($mid_low, 4); ++$i}
			<a href="{link page!, $i}"><span>{$i}</span></a>
		{/for}
		</td>

		<td class="tac">
		{for $i = $mid_low; $i <= $mid_high; ++$i}
			<a{attr class('active', $i == $paginator->getPage())} href="{link page!, $i}"><span>{$i}</span></a>
		{/for}
		</td>

		<td class="tar">
		{for $i = max($mid_high + 1, $paginator->getLastPage() - 2); $i <= ($paginator->getLastPage()); ++$i}
			<a href="{link page!, $i}"><span>{$i}</span></a>
		{/for}
		{if $paginator->isLast()}
			<span>Další&nbsp;&rsaquo;</span>
			<span>Poslední&nbsp;&raquo;</span>
		{else}
			<a{if $paginator->getLastPage() == $paginator->getPage()} class="inactive"{/if}  href="{link page!, $paginator->getPage() + 1}"><span>Další&nbsp;&rsaquo;</span></a>
			<a{if $paginator->getLastPage() == $paginator->getPage()} class="inactive"{/if}  href="{link page!, $paginator->getLastPage()}"><span>Poslední&nbsp;&raquo;</span></a>
		{/if}
		</td>
	</tr>
	</table>
	</div>
</div>
{/if}
