<?php
/**
 * @param	string			$title
 * @param	string			$subtitle			[optional]
 * @param	string			$link
 * @param	string			$description
 * @param	string			$language
 * @param	string			$copyright			[optional]
 * @param	string			$category			[optional]
 * @param	string			$docs
 * @param	array|string	$image				[optional]	Keys: url, title, link.

 * @param	array|$item		$items
 * @param	string			$item["title"]
 * @param	string			$item["link"]
 * @param	string			$item["guid"]		[optional]
 * @param	string			$item["description"]
 * @param	string			$item["category"]	[optional]
 * @param	string			$item["comments"]	[optional]
 * @param	string			$item["pubDate"]	[optional]
 */
?>
<?xml version=”1.0″ encoding=”utf-8″?>
<rss version="2.0">
	<channel>

		<title>{$title} - {if !empty($subtitle)} {$subtitle} {/if}</title>

		<link>{$link}</link>

		<description>{$description}</description>

		<language>{$language}</language>

		{if !empty($copyright)}
		<copyright>{$copyright}</copyright>
		{/if}

		{if !empty($category)}
		<category>{$category}</category>
		{/if}

		{if !empty($image)}
		<image>
			<url>{$image["url"]}</url>
			<title>{$image["title"]}</title>
			<link>{$image["title"]}</link>
		</image>
		{/if}

		{foreach $items AS $item}
			<item>
				<title>{$item["title"]}</title>
				<link>{$item["link"]}</title>
				{if !empty($item["guid"])}<guid>{$item["guid"]}</guid>{/if}
				<description>{$item["description"]}</description>
				{if !empty($item["category"])}<category>{$item["category"]}</category>{/if}
				{if !empty($item["comments"])}<comments>{$item["comments"]}</comments>{/if}
				<pubDate>{$item["pubDate"]}</pubDate>
			</item>
		{/foreach}

	</channel>

</rss>