<script type="text/javascript">
$(document).ready(function(){

    $(".toggle_container").hide();

    //Switch the "Open" and "Close" state per click then slide up/down (depending on open/close state)
    $(".shelf h2").click(function(){
	$(this).next().slideToggle("slow");
	
    });

    // Find if there is an anchor, if so then try to toogle the shelf
    var url = document.location.toString();
    if (url.match('#')) { // the URL contains an anchor
      var anchor = '#' + url.split('#')[1];
      $(anchor).parent().slideToggle("slow");
    }
});
</script>

<style>
    html {
	overflow-Y: scroll;
    }
    .shelf {
	margin-top: 5px;
	margin-left: 20px;
    }
    .shelf p {
	margin: 0;
    }
    .shelf ul {
	padding:0;
	list-style: none;
	margin-bottom: 20px;
	border: 2px solid #e9f4f7;
	border-top: 0px none;
	-webkit-border-radius: 0px 0px 5px 5px;
	-moz-border-radius: 0px 0px 5px 5px;
	border-radius: 0px 0px 5px 5px;
	padding: 10px;
    }
    .book-in-shelf {
	display: block;
	padding: 5px;
	margin: 0;
    }
    .book-in-shelf img {
	float: left;
	margin: 0 10px 0 0;
    }
    .book-in-shelf h3 {
	margin: 0;
    }
    .book-in-shelf:hover {
	background: #F9E7A2;
	-moz-border-radius: 5px;
	-webkit-border-radius: 5px;
	border-radius: 5px;
    }
    .shelf h2 {
	margin: 0;
	cursor: pointer;
	padding: 0 10px;
	line-height: 2em;
	font-weight: normal;
	-webkit-border-radius: 5px 5px 0px 0px;
	-moz-border-radius: 5px 5px 0px 0px;
	border-radius: 5px 5px 0px 0px;
	border: 2px solid #6699bb;
    }
    .shelf h2 .control {
	float: right;
	
    }
    .shelf h2 .control a {
	margin-right: 10px;
    }
    .shelf h2 span.number {
	font-size: 90%;
	color: black;
    }
    .new-pos-highlight {
	    background: #C1833E;
	    height: 2px;
	    width: 100%;
    }
    .shelf-type-wanted {
	background: #FDF7CD;
    }
    .shelf-type-owned {
	background: #E9F4F7;
    }
    .shelf-type-general {
	background: white;
    }
</style>

{foreach $shelves AS $shelf}

<div class="shelf">
	<h2 title="{$shelf->name}" class="shelf-type-{$shelf->type}">
	{$shelf->name|hardTruncate:40}
	{if Environment::getUser()->isAllowed(Resource::create($shelf), Action::EDIT)}
	    <span class="control">
		{assign confirm => System::translate("Are you sure you want to delete a shelf *%s*?", $shelf->name)}
		{assign link    => $component->link('remove', $shelf->getId())}
		<a href="{plink User:editShelf, System::user()->getId(), $shelf->getId()}" title="{_'Edit'}">
		    <img src="{$baseUri . 'img/ico/edit.png'}" alt="{_'Edit'}" />
		</a>
		<a onclick="if(confirm('{!$confirm}')) window.location = '{!$link}'" title="{_'Delete'}">
		    <img src="{$baseUri . 'img/ico/delete.png'}" alt="{_'Delete'}" />
		</a>
	    </span>
	{/if}
	<span class="number">({? echo count($books[$shelf->getId()]); })</span>
    </h2>
		    
    <div class="toggle_container">
	{if !empty($books[$shelf->getId()])}
	    {if Environment::getUser()->isAllowed(Resource::create($shelf), Action::EDIT)}
		{assign link => $component->link('persist', $shelf->getId())}
		<script>
		    $(function() {
			    $("#books-in-shelf-{!$shelf->getId()}").sortable({ placeholder: 'new-pos-highlight',opacity: 0.6, cursor: 'move', update: function() {
				    var order = $(this).sortable("serialize");
				    $.post("{!link}", order);
			    }
			    });
		    });
		</script>
	    {/if}
	    <ul class="books-in-shelf" id="books-in-shelf-{$shelf->getId()}">
		{foreach $books[$shelf->getId()] AS $bookRow}
		    {assign book => Leganto::books()->createEmpty()->loadDataFromArray($bookRow->toArray(), "Load")}
		    <li class="book-in-shelf" id="books_{$book->getId()}">
		    <img src="{$book->getId(), 25|bookcover}" width="25" height="40" />
		    <h3><a href="{plink Book:default, $book->getId()}">{$book->title}</a></h3>
		    <hr style="clear:both; visibility:hidden;" />
		</li>
		{/foreach}
	    </ul>
	{/if}
    </div>
</div>
{/foreach}